facebookresearch/theseus

theseus/geometry/se2.py
theseus/geometry/so2.py

This is a safer default for SE2 and SO2.
All tests passes. Tactile pose estimation example also works as expected.

Default SE2/SO2 is zero element rather than torch empty.

---

theseus/geometry/se2.py
theseus/geometry/so3.py
theseus/geometry/tests/test_so3.py

Taoshaf.check se2

---

theseus/geometry/se2.py
theseus/geometry/so3.py
theseus/geometry/tests/test_so3.py

Add SO3.exp_map() and SO3.log_map()

---

theseus/geometry/se2.py
theseus/geometry/so3.py
theseus/geometry/tests/test_so3.py

add SO3.hat() and SO3.vee()

---

theseus/core/tests/test_objective.py
theseus/geometry/se2.py
theseus/utils/examples/motion_planning/models.py

[hotfix] fix lint issues

---

.pre-commit-config.yaml
theseus/core/tests/test_objective.py
theseus/geometry/se2.py
theseus/geometry/so3.py
theseus/geometry/tests/test_so3.py
theseus/utils/examples/motion_planning/models.py

Add SO3.to_quaternion

---

setup.cfg
theseus/core/cost_function.py
theseus/core/tests/test_cost_function.py
theseus/optimizer/nonlinear/nonlinear_optimizer.py

Minor fixes 02/01/2022

---

theseus/geometry/se3.py
theseus/geometry/so3.py
theseus/geometry/tests/test_se3.py

add SE3.transform_from and SE3.transform_to

---

theseus/optimizer/nonlinear/nonlinear_optimizer.py
theseus/optimizer/nonlinear/tests/common.py

This decouples error history tracking from verbose setting.

Added kwarg to NonlinearOptimizer.optimizer() for tracking error history

---

theseus/optimizer/linear/lu_cuda_sparse_solver.py

Fix https://github.com/facebookresearch/theseus/issues/88
It's a case not triggered in test because of the mock-type use of classes in tests. This is not a problem because the tests indeed test the core of the functionality (apart from some possible oversight like this one, which is trivially fixable and will also be triggered in more complete end-to-end tests).
Swap two code lines.

Fix Issue 88

---

examples/README.md
examples/se2_inverse.py
theseus/__init__.py
theseus/geometry/__init__.py
theseus/geometry/lie_group.py
theseus/geometry/se2.py
theseus/geometry/se3.py
theseus/geometry/so2.py
theseus/geometry/so3.py
theseus/geometry/tests/test_se2.py
theseus/geometry/tests/test_se3.py
theseus/geometry/tests/test_so2.py
theseus/geometry/tests/test_so3.py
theseus/geometry/utils.py
theseus/geometry/vector.py

Add support for the automatic Jacobian and gradient computation on the Lie group tangent space.

Add automatic differentiation on the Lie group tangent space

---

theseus/geometry/se3.py
theseus/geometry/so3.py

Fix backpropagation bugs in SO3 and SE3 log_map

---

examples/configs/tactile_pose_estimation.yaml
examples/tactile_pose_estimation.py
theseus/utils/examples/tactile_pose_estimation/misc.py
theseus/utils/examples/tactile_pose_estimation/models.py
theseus/utils/examples/tactile_pose_estimation/pose_estimator.py

@psodhi I added batching support, if you could take a look to double check everything that would be great!

Added batching support to tactile pushing example.

---

.circleci/config.yml
theseus/geometry/point_types.py
theseus/geometry/tests/point_types_mypy_check.py
theseus/geometry/tests/test_point_types.py

Overrides vector operations for `Point2`, `Point3` #113

Override Vector operators in Point2 and Point3

---

theseus/core/objective.py

Fix a bug in Objective.copy()

---

.pre-commit-config.yaml

This PR is intent to close the issue #142

black version bump

---

theseus/core/tests/test_objective.py
theseus/optimizer/tests/linearization_test_utils.py
theseus/tests/test_theseus_layer.py

All unit tests seems passed for batch processing

---

examples/pose_graph_synthetic.py
theseus/core/objective.py
theseus/utils/examples/tactile_pose_estimation/pose_estimator.py

Tactile pushing example works for batch processing

---

examples/configs/tactile_pose_estimation.yaml
examples/tactile_pose_estimation.py
theseus/utils/examples/tactile_pose_estimation/misc.py
theseus/utils/examples/tactile_pose_estimation/trainer.py

cc @fantaosha, need to merge this to experimental.

Add-ons for backward experiments on Tactile Pose Estimation

---

theseus/optimizer/nonlinear/nonlinear_optimizer.py
theseus/utils/examples/tactile_pose_estimation/pose_estimator.py

Fix the in-place operation bug

---

examples/configs/pose_graph.yaml
examples/pose_graph_synthetic.py
theseus/core/cost_function.py
theseus/utils/examples/pose_graph/dataset.py

PGO profiling

---

theseus/core/objective.py
theseus/optimizer/dense_linearization.py
theseus/optimizer/nonlinear/nonlinear_optimizer.py
theseus/optimizer/sparse_linearization.py
theseus/utils/examples/tactile_pose_estimation/models.py
theseus/utils/examples/tactile_pose_estimation/pose_estimator.py

Shared aux vars

---

examples/pose_graph_synthetic.py
theseus/optimizer/linear/lu_cuda_sparse_solver.py
theseus/optimizer/nonlinear/nonlinear_optimizer.py

Add varying batch size support for LUCudaSparseSolver

---

examples/pose_graph_synthetic.py
theseus/core/loss_function.py
theseus/optimizer/linear/lu_cuda_sparse_solver.py
theseus/optimizer/nonlinear/nonlinear_optimizer.py

Fix loss function rescale bug

---

examples/backward_modes.py
examples/configs/tactile_pose_estimation.yaml
examples/tactile_pose_estimation.py
theseus/core/cost_function.py
theseus/core/objective.py
theseus/embodied/collision/collision.py
theseus/embodied/collision/eff_obj_contact.py
theseus/optimizer/nonlinear/nonlinear_optimizer.py
theseus/optimizer/nonlinear/tests/test_backwards.py
theseus/theseus_layer.py
theseus/utils/examples/tactile_pose_estimation/misc.py
theseus/utils/examples/tactile_pose_estimation/trainer.py
theseus/utils/utils.py

PGO for ablation 

---

theseus/core/robust_cost_function.py

Fixed the rescaling bug for robust cost function

---

.gitignore
theseus/geometry/se3.py
theseus/geometry/tests/test_se3.py

Fixed the cross product bug for SE3.exp_map and SE3.log_map

---

theseus/constants.py
theseus/geometry/se2.py
theseus/geometry/se3.py
theseus/geometry/so2.py
theseus/geometry/so3.py
theseus/geometry/tests/common.py
theseus/geometry/tests/test_se2.py
theseus/geometry/tests/test_se3.py
theseus/geometry/tests/test_so2.py
theseus/geometry/tests/test_so3.py
theseus/optimizer/tests/test_manifold_gaussian.py

SE2/SE3/SO3 - consolidate EPS, add dtype-conditioned EPS and add float32 unit tests

---

theseus/constants.py
theseus/geometry/manifold.py
theseus/geometry/se2.py
theseus/geometry/se3.py
theseus/geometry/so2.py
theseus/geometry/so3.py
theseus/geometry/tests/common.py
theseus/geometry/tests/test_se2.py
theseus/geometry/tests/test_se3.py
theseus/geometry/tests/test_so2.py
theseus/geometry/tests/test_so3.py
theseus/geometry/vector.py

Add normalization to Lie group

---

theseus/optimizer/nonlinear/nonlinear_optimizer.py

Added state history tracking

---

examples/pose_graph/pose_graph_benchmark.py
examples/pose_graph/pose_graph_cube.py

update pose graph data link

---

tutorials/00_introduction.ipynb

Syntax error on Cell 7. There's a missing comma after "w1".
`cf1 = th.Difference(x, a, w1 name="term_1")`
Restarted the kernel and cleared outputs for the notebook, proceeded to run all cells. Received same syntax error.
Added the comma in to prevent syntax error.

Small Update to 00_introduction.ipynb

---

examples/homography_estimation.py

Fix a bug on the homography estimation example https://github.com/facebookresearch/theseus/issues/274
Followed the steps on bug https://github.com/facebookresearch/theseus/issues/274. The examples works after the changes.

Bugfix: homography estimation - create data folder before downloading data

---

.circleci/config.yml
requirements/main.txt
theseus/core/cost_function.py
theseus/core/tests/test_cost_function.py
theseus/geometry/lie_group_check.py
theseus/geometry/manifold.py
theseus/geometry/se3.py
theseus/geometry/so2.py
theseus/geometry/so3.py
theseus/geometry/tests/common.py
theseus/geometry/tests/test_se2.py
theseus/geometry/tests/test_se3.py
theseus/geometry/tests/test_so2.py
theseus/geometry/tests/test_so3.py

Add functorch support for AutoDiffCostFunction

---

theseus/geometry/se2.py
theseus/geometry/se3.py
theseus/geometry/so3.py
theseus/geometry/tests/test_se3.py

Add to_quaternion, rotation, translation and convention comment

---

theseus/__init__.py
theseus/core/__init__.py
theseus/core/cost_weight.py
theseus/core/variable.py
theseus/embodied/collision/collision.py
theseus/embodied/collision/eff_obj_contact.py
theseus/embodied/collision/signed_distance_field.py
theseus/embodied/motionmodel/double_integrator.py
theseus/embodied/motionmodel/quasi_static_pushing_planar.py

Works similar to `torch.as_tensor()` to return a new `Variable`. We can also pass the name.

Added th.as_variable() function to simplify creating new variables.

---

theseus/optimizer/nonlinear/nonlinear_optimizer.py
theseus/optimizer/nonlinear/tests/common.py

This would be useful for visualization and debugging during optimization.
The unit tests check that the callback is called with the right type of data.

Added an optional end-of-step callback to NonlinearOptimizer.optimize().

---

theseus/__init__.py
theseus/core/__init__.py
theseus/core/cost_function.py
theseus/core/tests/test_cost_function.py
theseus/geometry/tests/common.py

Add AutogradMode to AutoDiffCostFunction

---

theseus/core/tests/common.py
theseus/core/tests/test_cost_weight.py
theseus/core/tests/test_robust_cost.py
theseus/core/tests/test_vectorizer.py
theseus/embodied/collision/tests/test_collision_factor.py
theseus/embodied/collision/tests/test_eff_obj_contact.py
theseus/embodied/collision/tests/test_signed_distance_field.py
theseus/embodied/measurements/tests/test_between.py
theseus/embodied/measurements/tests/test_moving_frame_between.py
theseus/embodied/misc/tests/test_variable_difference.py
theseus/embodied/motionmodel/tests/test_double_integrator.py
theseus/embodied/motionmodel/tests/test_quasi_static_pushing_planar.py
theseus/geometry/tests/common.py
theseus/geometry/tests/test_point_types.py
theseus/geometry/tests/test_se2.py
theseus/geometry/tests/test_se3.py
theseus/geometry/tests/test_so2.py
theseus/geometry/tests/test_so3.py
theseus/geometry/tests/test_vector.py
theseus/tests/test_dlm_perturbation.py

Changed unit tests so that the batch sizes to tests are defined in a central import

---

theseus/core/objective.py

Issue: https://github.com/facebookresearch/theseus/issues/301
Motivation: Objective.add(CostFunction) execution time will increase with the number of optimization problems. If I want to construct 20000+ odometry constraints, it will need 200+ seconds. It is too slow. The reason is that time consuming of https://github.com/facebookresearch/theseus/blob/main/theseus/core/objective.py#L198 increases with the number of problems.
Solution: We only need to judge whther the newly appended aux/optim variables are in the  optim/aux variables. Not need to compare all  variables.
Safety: The modificated Objective has passed the unit test in test_objective.py. It means that the Objective.add(CostFunction) could detect optim variables and aux variables with duplicate names.
Time consuming: I …

enhance the efficiency of Objectve.add()

---

theseus/geometry/so3.py

Fixed quaternion bug at pi

---

theseus/core/cost_function.py
theseus/geometry/lie_group_check.py
theseus/geometry/manifold.py
theseus/geometry/se2.py
theseus/geometry/se3.py
theseus/geometry/so2.py
theseus/geometry/so3.py
theseus/geometry/tests/common.py
theseus/geometry/tests/test_se3.py
theseus/geometry/tests/test_so3.py

There were too many warnings in our unit tests. I think this removed something like 650 warnings (this is not hyperbole).

Added option for making LieGroup checks silent.

---

tests/optimizer/nonlinear/test_levenberg_marquardt.py
tests/test_theseus_layer.py
theseus/optimizer/linear/dense_solver.py
theseus/optimizer/nonlinear/levenberg_marquardt.py

This PR adds a few small fixes that I found when working on #371. Somehow none of us noticed that the loss in `test_theseus_layer` was actually missing a square! I also removed a test that's no longer needed for LM.

Added missing square in `test_theseus_layer` loss.

---

tests/geometry/functional/test_so3.py
theseus/geometry/functional/lie_group.py
theseus/geometry/functional/so3.py

Add theseus.geometry.functional.so3.adjoint()

---

setup.py

Made torch's CUDA_GCC_VERSION check optional in setup.py.

---

tests/geometry/functional/test_so3.py
theseus/geometry/functional/so3.py

Add hat() and vee() operators to theseus.geometry.so3

---

tests/geometry/functional/test_se3.py
theseus/geometry/functional/se3.py

Add se3.left_project()

---

tests/geometry/functional/test_se3.py
theseus/geometry/functional/se3.py

Add se3.left_act()

---

tests/geometry/functional/test_se3.py
theseus/geometry/functional/se3.py

Add se3.lift() and se3.project()

---

tests/geometry/functional/test_se3.py
theseus/geometry/functional/se3.py

Add se3.compose()

---

tests/geometry/functional/test_se3.py
theseus/geometry/functional/se3.py

Add se3.hat() and se3.vee()

---

tests/geometry/functional/test_se3.py
theseus/geometry/functional/se3.py

Add `functional.se3.inverse()`

Add se3.inverse()

---

tests/geometry/functional/test_se3.py
theseus/geometry/functional/se3.py

Add se3.adjoint()

---

tests/geometry/functional/test_se3.py
theseus/geometry/functional/se3.py

Add se3.exp()

---

tests/geometry/functional/common.py
tests/geometry/functional/test_se3.py
tests/geometry/functional/test_so3.py
theseus/geometry/functional/se3.py
theseus/geometry/functional/so3.py

Add so3.log()

---

tests/geometry/functional/common.py
tests/geometry/functional/test_se3.py
tests/geometry/functional/test_so3.py
theseus/geometry/functional/lie_group.py
theseus/geometry/functional/se3.py
theseus/geometry/functional/so3.py

The `left_project()` operator is original project operator.

Add left_project() to theseus.geometry.functional.so3

---

tests/geometry/functional/common.py
tests/geometry/functional/test_se3.py
tests/geometry/functional/test_so3.py
theseus/geometry/functional/lie_group.py
theseus/geometry/functional/se3.py
theseus/geometry/functional/so3.py

Add left_act() to theseus.geometry.functional.so3

---

tests/geometry/functional/common.py
tests/geometry/functional/test_se3.py
tests/geometry/functional/test_so3.py
theseus/geometry/functional/lie_group.py
theseus/geometry/functional/se3.py
theseus/geometry/functional/so3.py

The `lift()` and `project()` only operates on the Lie algebra and are different from our previous implementation. In the future, we will further `left_lift()`, `right_lift()`, `left_project()` and `right_project()` on the tangent space.

Add lift() and project() to theseus.geometry.functional.so3

---

tests/geometry/functional/common.py
tests/geometry/functional/test_se3.py
tests/geometry/functional/test_so3.py
theseus/geometry/functional/lie_group.py
theseus/geometry/functional/se3.py
theseus/geometry/functional/so3.py

Add rand() and randn() to theseus.geometry.functional.so3

---

tests/geometry/functional/common.py
tests/geometry/functional/test_se3.py
tests/geometry/functional/test_so3.py
theseus/geometry/functional/lie_group.py
theseus/geometry/functional/se3.py
theseus/geometry/functional/so3.py

Add quaternion_to_rotation() to theseus.geometry.functional.so3

---

tests/geometry/functional/test_se3.py
theseus/geometry/functional/se3.py
theseus/geometry/functional/so3.py

Taoshaf.functional.se3.rand

---

tests/optimizer/nonlinear/test_backwards.py
theseus/optimizer/autograd/baspacho_sparse_autograd.py
theseus/optimizer/autograd/cholmod_sparse_autograd.py
theseus/optimizer/autograd/common.py
theseus/optimizer/autograd/lu_cuda_sparse_autograd.py
theseus/optimizer/linear/baspacho_sparse_solver.py
theseus/optimizer/linear/cholmod_sparse_solver.py
theseus/optimizer/linear/lu_cuda_sparse_solver.py
theseus/optimizer/nonlinear/nonlinear_optimizer.py
theseus/optimizer/sparse_linearization.py

This adds support for detaching the hessian contribution to `A_grad` in the sparse solvers

---

.circleci/config.yml
tests/labs/lie_functional/common.py
tests/labs/lie_functional/test_se3.py
tests/labs/lie_functional/test_so3.py
theseus/labs/lie_functional/lie_group.py
theseus/labs/lie_functional/se3.py
theseus/labs/lie_functional/so3.py

Add Lie groups functional library

---

examples/motion_planning_2d.py
examples/pose_graph/pose_graph_benchmark.py
examples/state_estimation_2d.py
tests/core/test_objective.py
tests/core/test_vectorizer.py
tests/optimizer/nonlinear/common.py
tests/optimizer/nonlinear/test_trust_region.py
tests/test_dlm_perturbation.py
theseus/core/objective.py
theseus/optimizer/nonlinear/levenberg_marquardt.py
theseus/optimizer/nonlinear/nonlinear_least_squares.py
theseus/optimizer/nonlinear/nonlinear_optimizer.py
theseus/optimizer/nonlinear/trust_region.py
theseus/theseus_layer.py
theseus/utils/examples/motion_planning/motion_planner.py
tutorials/00_introduction.ipynb
tutorials/02_differentiating_theseus_layer.ipynb
tutorials/03_custom_cost_functions.ipynb
tutorials/05_differentiable_motion_planning.ipynb

Continues work from #440
@rtqichen tagging you to double check DLM changes.

Moved error metric to Objective

---

tests/embodied/robot/test_forward_kinematics.py
theseus/embodied/robot/joint.py
theseus/embodied/robot/robot.py

Refactor Joint.dof as a property

---

.circleci/config.yml
tests/labs/lie/functional/common.py
tests/labs/lie/functional/test_se3.py
tests/labs/lie/functional/test_so3.py
tests/labs/lie/test_lie_tensor.py
theseus/labs/lie/__init__.py
theseus/labs/lie/functional/lie_group.py
theseus/labs/lie/functional/se3_impl.py
theseus/labs/lie/functional/so3_impl.py
theseus/labs/lie/lie_tensor.py

Add transform_from to Lie group

---

tests/labs/embodied/robot/test_forward_kinematics.py
tests/labs/lie/functional/test_se3.py
theseus/labs/embodied/robot/forward_kinematics.py
theseus/labs/embodied/robot/joint.py
theseus/labs/embodied/robot/robot.py
theseus/labs/lie/functional/__init__.py
theseus/labs/lie/functional/lie_group.py
theseus/labs/lie/functional/se3_impl.py
theseus/labs/lie/functional/so3_impl.py
theseus/labs/lie/lie_tensor.py
theseus/labs/lie/types.py

Lie Labs API v3

---

theseus/labs/lie/functional/se3_impl.py
theseus/labs/lie/functional/so3_impl.py
theseus/labs/lie/functional/utils.py

Update checks to be consistent with multi-batch implementation

---

tests/labs/lie/functional/common.py
theseus/labs/lie/functional/se3_impl.py
theseus/labs/lie/functional/so3_impl.py
theseus/labs/lie/functional/utils.py

Add multi-batch compose() and transform_from() for SO(3) and SE(3)

---

tests/labs/lie/functional/common.py
theseus/labs/lie/functional/lie_group.py
theseus/labs/lie/functional/se3_impl.py
theseus/labs/lie/functional/so3_impl.py
theseus/labs/lie/functional/utils.py

Implemented multi-batch gradient ops

---

tests/theseus_tests/core/test_vectorizer.py
theseus/geometry/se3.py
theseus/geometry/so3.py

Reverts facebookresearch/theseus#524

Revert "Migrate SO3 to use `torchlie`"

---

tests/theseus_tests/core/test_vectorizer.py
theseus/geometry/se3.py
theseus/geometry/so3.py

Copy of #524, which I merged to the wrong branch unintentionally.

Migrate SO3 (reissue)

---

docs/source/conf.py
docs/source/core.rst
docs/source/generated/theseus.CostFunction.rst
docs/source/generated/theseus.Objective.add.rst
docs/source/generated/theseus.Objective.error.rst
docs/source/generated/theseus.Objective.retract_vars_sequence.rst
docs/source/generated/theseus.Objective.rst
docs/source/generated/theseus.Objective.update.rst
theseus/core/cost_function.py
theseus/core/objective.py

You can check the current version [here](https://theseus-ai.readthedocs.io/en/lep.add_some_docs_pt1/index.html).

Adding some docs

---

theseus/geometry/so3.py

Fix SO3 rotate check

---

tests/torchlie_tests/functional/common.py
tests/torchlie_tests/functional/test_se3.py
tests/torchlie_tests/functional/test_so3.py
tests/torchlie_tests/test_lie_tensor.py
theseus/geometry/se3.py
theseus/geometry/so3.py
torchlie/torchlie/__init__.py
torchlie/torchlie/functional/lie_group.py
torchlie/torchlie/functional/se3_impl.py
torchlie/torchlie/functional/so3_impl.py
torchlie/torchlie/lie_tensor.py

transform_from -> transform

---

theseus/geometry/se2.py
theseus/global_params.py

Add `d_near_zero` to `SE2`

---

torchkin/README.md

Add torchkin example

---

torchkin/torchkin/joint.py

fixed a bug in prismatic joint

---

examples/tactile_pose_estimation.py
tests/theseus_tests/test_pgo_benchmark.py
tests/theseus_tests/test_theseus_layer.py
theseus/core/objective.py

Prevent update variables with device or dtype != Objective's

---

examples/homography_estimation.py
examples/pose_graph/pose_graph_benchmark.py
examples/pose_graph/pose_graph_cube.py
examples/pose_graph/pose_graph_synthetic.py
tests/theseus_tests/core/test_objective.py
tests/theseus_tests/core/test_vectorizer.py
tests/theseus_tests/test_dlm_perturbation.py
tests/theseus_tests/test_theseus_layer.py
theseus/core/objective.py
theseus/theseus_layer.py
theseus/utils/examples/tactile_pose_estimation/pose_estimator.py

`Objective.to()` and `TheseusLayer.to()` now return `self` and support "cuda".

---

evaluations/time_local_cost_backward.py
examples/se2_planning.py
tests/torchlie_tests/functional/common.py
tests/torchlie_tests/functional/test_se3.py
tests/torchlie_tests/functional/test_so3.py
theseus/_version.py
theseus/embodied/misc/local_cost_fn.py
theseus/global_params.py
torchlie/torchlie/__init__.py
torchlie/torchlie/functional/lie_group.py
torchlie/torchlie/functional/se3_impl.py
torchlie/torchlie/functional/so3_impl.py
torchlie/torchlie/global_params.py
tutorials/05_differentiable_motion_planning.ipynb

Copy of #627, which was incorrectly merged to another branch. This PR sets the target directly to main. No other changes.

Faster log map implementation

---

tests/torchlie_tests/test_lie_tensor.py
torchlie/torchlie/lie_tensor.py

Fix broken backward graph when using `LieTensor.exp()`

---

theseus/_version.py
theseus/geometry/so3.py
theseus/global_params.py

Add EPS for sqrt in SO3 to_quaternion
