- .gitattributes
- CONTRIBUTING.md
- Update contributing file to the branching model we follow.
- Added gitattribute file (to ignore .pynb files) to display correct language on landing page.
> Update contrib and add gitattributes

- theseus/__init__.py
- theseus/geometry/__init__.py
- theseus/geometry/se2.py
- theseus/geometry/so3.py
- theseus/geometry/tests/test_so3.py
Part of work for adding support for 3D geometry (SO3 and SE3). 
This class is just a stub with no new functionality added, just outlining the core abstract method that need to be filled out.
> Add SO3 support

- theseus/__init__.py
- theseus/geometry/__init__.py
- theseus/geometry/se3.py
- theseus/geometry/so3.py
- theseus/geometry/tests/test_se3.py
- theseus/geometry/tests/test_so3.py
> add adjoint, hat and vee for SE3

- README.md
pip installation fails if libsuitesparse is not pre-installed. 
Installation works on new environments in Mac and collab notebook if the steps in the new README are followed.
> Updated README with libsuitesparse installation instructions.

- theseus/optimizer/nonlinear/nonlinear_optimizer.py
> Merge infos results for truncated backward modes

- theseus/optimizer/nonlinear/nonlinear_optimizer.py
Our current derivation of implicit/truncated backward modes hols only for Gauss-Newton. However, regardless of the optimization method used, we can first find the fixed point, then force the optimizer to apply a GN step. Preliminary experiments with Levenberg-Marquardt show that this improves the error in gradient computation, compared with numerical derivatives. 
Marking as bugfix, since this means that previous version of LM was incorrect.
> Forced Gauss-Newton step for last iterations of truncated backward.

- noxfile.py
- theseus/core/objective.py
- theseus/optimizer/linear/lu_cuda_sparse_solver.py
- theseus/optimizer/nonlinear/levenberg_marquardt.py
- theseus/optimizer/nonlinear/tests/test_levenberg_marquardt.py
- theseus/optimizer/sparse_linearization.py
> Enabled back ellipsoidal damping in LM with linear solvers support checks

- theseus/core/objective.py
- theseus/core/tests/test_objective.py
API improvement in Objective: error and errorSquaredNorm can optionally take in var_data which if passed would call update internally. Document the behavior that if var_data is passed this will update the objective. #4 
Testes using unit test and a custom example
> error and errorsquaredNorm optional data

- theseus/embodied/collision/collision.py
- theseus/embodied/collision/eff_obj_contact.py
- theseus/embodied/kinematics/robot_model.py
> Change RobotModel.forward_kinematics() interface

- theseus/utils/examples/__init__.py
Since core functionality doesn't depend on `matplotlib` and `omegaconf`, I think it's better to keep these installations optional. However, looks like the missing dependencies are breaking the test code in CI, so I added try/catch around import error with a warning message.
> Added error handling for missing `matplotlib` and `omegaconf` installation when using `theg`

- theseus/geometry/lie_group.py
> Add jacobians argument to exp_map and log_map functions

- examples/pose_graph.py
- theseus/embodied/measurements/between.py
- theseus/geometry/se3.py
- theseus/geometry/so3.py
- theseus/utils/examples/pose_graph/dataset.py
> Merge `Between` and `VariableDiff` with `RelativePoseError` and `PosePriorError`

- theseus/embodied/collision/collision.py
- theseus/embodied/collision/eff_obj_contact.py
- theseus/embodied/kinematics/robot_model.py
It was not currently used for anything important and it's not clear that it will ever be needed.
> Removed RobotModel.dim()

- theseus/embodied/motionmodel/double_integrator.py
Fixes a bug where updating `dt` with the correct scalar shape results in error, as shown below.
> [bug-fix] Fixed wrong data shape initialization for GPCostWeight.dt

- theseus/core/cost_function.py
This preserves optimization variables types and can solve errors like [this](https://github.com/facebookresearch/theseus/pull/84#discussion_r847801204). 
Besides running unit tests, I also ran the `backward_modes.py` script and the first tutorial. Seems to be working w/o issues after this change. 
cc @exhaustin
> Made AutoDiffCostFunction._tmp_optim_vars copies of original

- theseus/geometry/se3.py
> Fixed dtype error in `se3.py` that came up in unit tests

- .circleci/config.yml
- README.md
- theseus/geometry/tests/test_point_types.py
> Change unit tests to avoid making mypy a main requirement.

- requirements/main.txt
- theseus/embodied/kinematics/kinematics_model.py
- theseus/embodied/kinematics/tests/test_urdf_model.py
Fixes issue #123 
An update was pushed to the Differentiable Robot Model that allows for computing forward kinematics for all links in one call.
This PR bumps the DRM version dependency and modifies the interface to obtain poses for all links in a single call.
Note: Small numerical deviations cause the original tests to fail. However the output of forward kinematics is being checked against PyBullet on the DRM side, which are all passing. Given this knowledge, the computed outputs of the original implementation is not any more accurate than the current one. Tolerances for the failing tests were relaxed a reasonable amount to account for the numerical differences from the original.
> More efficient implementation of forward kinematics

- theseus/embodied/collision/collision.py
- theseus/embodied/collision/eff_obj_contact.py
- theseus/utils/utils.py
… updated.
Calling `Objective.copy()` when there are `Collision2D` or `EffectorObjectContactPlanar` cost functions resulted in incorrect behavior, because the `sdf_data` variable container created was not being linked to the underlying `PlanarSDF` objects.  
I ran the code in #161 and seems to be working (where this bug was first detected).
> Updated SDF object in collision cost functions whenever an aux var is updated

- theseus/core/tests/common.py
- theseus/core/tests/test_theseus_function.py
- theseus/core/theseus_function.py
We are using copy to create new variables in the cost function vectorization code, and this would help avoid some unwanted bugs if an user creates a new cost function that re-uses some of the old variables rather than copying.
> Added a check in TheseusFunction that enforces copy() also copies the variables

- .gitignore
- README.md
Add notes on python version (required for scikit sparse) and on CUDA installation.
Built on my machine
- [X ] Docs change / refactoring / dependency upgrade
> Update README to specify python versions and CUDA during install step +

- theseus/core/objective.py
- theseus/optimizer/linear/linear_optimizer.py
- theseus/optimizer/nonlinear/nonlinear_optimizer.py
- theseus/theseus_layer.py
We have talked for quite a while about where to place this method. Proposing the solution in this PR. Planning to use this as the starting point for the vectorized retraction maps.
> Moved the method that retracts all variables with a given delta to Objective

- theseus/core/objective.py
- theseus/core/tests/test_robust_cost.py
- theseus/core/vectorizer.py
- theseus/embodied/kinematics/tests/test_inverse_kinematics.py
- theseus/optimizer/linear/linear_optimizer.py
- theseus/optimizer/nonlinear/gauss_newton.py
- theseus/optimizer/nonlinear/levenberg_marquardt.py
- theseus/optimizer/nonlinear/nonlinear_least_squares.py
- theseus/optimizer/nonlinear/nonlinear_optimizer.py
- theseus/optimizer/nonlinear/tests/common.py
- theseus/optimizer/nonlinear/tests/test_backwards.py
- theseus/optimizer/optimizer.py
- theseus/tests/test_theseus_layer.py
- theseus/theseus_layer.py
Note that the old stand-alone optimizer tests have `vectorize=False` because the copy method of the CostFunction used is not implemented. It's kind of a pain to implement it for not a lot of added value, since the end-to-end and backward tests do use vectorization.
> Moved Vectorize(objective) to the Optimizer class.

- theseus/tests/test_dlm_perturbation.py
- theseus/theseus_layer.py
Tested with 64-bit precision. 32-bit precision fails. We should address with #61.
> Added close-formed jacobian for DLM perturbation cost.

- examples/bundle_adjustment.py
- examples/pose_graph/pose_graph_cube.py
- examples/pose_graph/pose_graph_synthetic.py
- theseus/core/objective.py
- theseus/core/tests/common.py
- theseus/core/tests/test_manifold.py
- theseus/core/tests/test_objective.py
- theseus/core/vectorizer.py
- theseus/geometry/lie_group.py
- theseus/geometry/manifold.py
- theseus/geometry/point_types.py
- theseus/geometry/se2.py
- theseus/geometry/se3.py
- theseus/geometry/so2.py
- theseus/geometry/so3.py
- theseus/geometry/tests/common.py
- theseus/geometry/vector.py
- theseus/optimizer/tests/linearization_test_utils.py
- theseus/tests/test_theseus_layer.py
- theseus/theseus_layer.py
Renaming some additional methods and variables, mostly for consistency.
> More data -> tensor renaming

- examples/homography_estimation.py
- theseus/third_party/easyaug.py
Also reduces the default training dataset size, lowering the "time to fun" :)
Gives proper attribution to kornia team's hard work, makes the easyaug.py file more clean and smaller.
python homography_example.py
- [ x] My code follows the code style of this project.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] I have completed my CLA (see **CONTRIBUTING**)
> [homography] Use kornia lib properly for perspective transform

- examples/motion_planning_2d.py
- theseus/utils/examples/__init__.py
- theseus/utils/examples/motion_planning/__init__.py
- theseus/utils/examples/motion_planning/models.py
- theseus/utils/examples/motion_planning/motion_planner.py
- tutorials/04_motion_planning.ipynb
- tutorials/05_differentiable_motion_planning.ipynb
Motion planner objective can be created separately, allowing one to modify the objective before wrapping in an optimizer and `TheseusLayer`. Note that this is a breaking change, old `MotionPlanner` code won't work anymore. 
Closes #272
> Refactored MotionPlanner so that objective can be passed separately.

- setup.py
To build wheels with Baspacho, users can now do 
`BASPACHO_ROOT_DIR=/my/path/ python -m build --no-isolation`
I'm still unclear how does this interact with `pip install -e .`.
> Cleanup Baspacho setup

- README.md
- examples/backward_modes.py
- examples/bundle_adjustment.py
- examples/homography_estimation.py
- examples/pose_graph/pose_graph_synthetic.py
- examples/simple_example.py
- theseus/optimizer/nonlinear/nonlinear_optimizer.py
- theseus/optimizer/nonlinear/tests/test_backwards.py
- theseus/tests/test_dlm_perturbation.py
- theseus/theseus_layer.py
- theseus/utils/examples/tactile_pose_estimation/trainer.py
We can now pass strings to specify backward modes, instead of having to pass the specific enum type.
> Rename BackwardMode.FULL --> UNROLL and simplify backward mode config

- examples/homography_estimation.py
- theseus/core/cost_function.py
- theseus/core/tests/test_cost_function.py
Autograd mode can now also be passed as a string.
> Simplified autograd mode specification.

- examples/simple_example.py
Modified `torch.exp(c * x)` to `return c * torch.exp(x)`.
> Fixing simple example

- README.md
- build_scripts/build_wheel.sh
- docs/source/getting-started.rst
- setup.cfg
- theseus/__init__.py
- theseus/constants.py
- theseus/extlib/tests/test_baspacho.py
- theseus/extlib/tests/test_baspacho_simple.py
- theseus/optimizer/autograd/tests/test_baspacho_sparse_backward.py
- theseus/optimizer/linear/tests/test_baspacho_sparse_solver.py
Main changes:
* Changed build script so that it always does the equivalent of `THESEUS_FORCE_CUDA=1`. This argument no longer needs to be passed.
* Hardcoded CUDA archs in the build script for. I'm guessing this  might be controversial, but couldn't get this to compile otherwise.
* Fixed build script so that it works with CPU-only install.
* Removed pytest baspacho marker. I don't think it's needed because tests are skipped automatically if BaSpaCho is not found.
* Added clearer README instructions. 
* Added a preliminary version bump (0.1.2rc1) as the build script requires a tag to work properly.
> Cleaned up Baspacho install, tests and README

- theseus/core/objective.py
- theseus/core/vectorizer.py
This PR commits two changes:
- Don't expand tensors in vectorization if the objective's batch size = 1
- Retract all variables now updates vectorization immediately, which avoids some cases were vectorization had to be run twice with the same data (because of torch.no_grad() uses). 
TODO: check if this changes times in the PGO benchmark. In a small BA script it looks like this leads to some improvements in running time (~10-20%).
> Small vectorization improvements

- .circleci/config.yml
- build_scripts/build_wheel.sh
- requirements/main.txt
Closes #341 
Made default funtorch <=0.2.1. Took some parts from #341 for CUDA11 in CI, and also changed build script to handle CUDA 10.2 and 11.3 separately.
> Change CI to separately handle torch >= 1.13

- theseus/extlib/baspacho_solver.cpp
- theseus/extlib/baspacho_solver.h
- theseus/extlib/baspacho_solver_cuda.cu
- theseus/extlib/mat_mult.cu
- theseus/extlib/tests/test_baspacho.py
- theseus/extlib/tests/test_cusolver_lu_solver.py
- theseus/extlib/tests/test_mat_mult.py
- theseus/extlib/utils.h
- theseus/optimizer/autograd/baspacho_sparse_autograd.py
- theseus/optimizer/autograd/lu_cuda_sparse_autograd.py
- theseus/optimizer/autograd/tests/__init__.py
- theseus/optimizer/autograd/tests/test_baspacho_sparse_backward.py
- theseus/optimizer/autograd/tests/test_lu_cuda_sparse_backward.py
- theseus/optimizer/linear/baspacho_sparse_solver.py
- theseus/optimizer/linear/cholmod_sparse_solver.py
- theseus/optimizer/linear/dense_solver.py
- theseus/optimizer/linear/linear_solver.py
- theseus/optimizer/linear/lu_cuda_sparse_solver.py
- theseus/optimizer/linear/sparse_utils.py
- theseus/optimizer/linear/tests/test_baspacho_sparse_solver.py
- theseus/optimizer/linear/tests/test_dense_solver.py
- theseus/optimizer/linear/tests/test_lu_cuda_sparse_solver.py
- theseus/optimizer/linear/utils.py
- theseus/optimizer/nonlinear/levenberg_marquardt.py
- theseus/optimizer/nonlinear/nonlinear_optimizer.py
- theseus/optimizer/nonlinear/tests/test_levenberg_marquardt.py
- theseus/utils/sparse_matrix_utils.py
This PR adds adaptive damping for LM, based on Section 4 of [this](https://people.duke.edu/~hpgavin/ce281/lm.pdf) reference. It includes a number of features:
- Allow independent step sizes for each batch element (not used in this PR).
- Include a `reset()` method for nonlinear optimizers that's called at the start of each optimization. We could also have it call the linear solver's reset method, although in some of the current sparse solvers this is costly (@maurimo to confirm).
- Include a `update_optimizer_step()` method for nonlinear optimizers. 
- Add an implementation of the above for LM to allow adaptive damping.
This feature is currently only compatible with dense solvers. @maurimo how likely is that we could add support for this in the sparse solvers?
As an added bonus of this …
> Adaptive damping for Levenberg-Marquardt

- tests/embodied/kinematics/test_urdf_model.py
- theseus/embodied/kinematics/kinematics_model.py
Existing Feature Request: https://github.com/facebookresearch/theseus/issues/355
Updated tests in `tests/embodied/kinematics/test_urdf_model.py`. 
The test currently defaults to `device=cuda:0` if cuda exists: https://github.com/thomasweng15/theseus/blob/3faa926334584596684eaadf0f082c4950ee763e/tests/embodied/kinematics/test_urdf_model.py#L24. 
But I have also tested with `device=cpu`. 
In both cases the tests pass.
> #355 Add device parameter to UrdfRobotModel

- MANIFEST.in
- theseus/__init__.py
- theseus/constants.py
- theseus/core/objective.py
- theseus/core/variable.py
- theseus/embodied/kinematics/kinematics_model.py
- theseus/geometry/lie_group.py
- theseus/geometry/point_types.py
- theseus/geometry/se2.py
- theseus/geometry/se3.py
- theseus/geometry/so2.py
- theseus/geometry/so3.py
- theseus/geometry/vector.py
- theseus/optimizer/linear/utils.py
- theseus/theseus_layer.py
- theseus/utils/examples/motion_planning/motion_planner.py
- theseus/utils/examples/pose_graph/dataset.py
- theseus/utils/examples/tactile_pose_estimation/misc.py
- theseus/utils/examples/tactile_pose_estimation/models.py
- theseus/utils/examples/tactile_pose_estimation/pose_estimator.py
- theseus/utils/examples/tactile_pose_estimation/trainer.py
This PR also adds a file `py.typed` so that `mypy` knows how to use our type annotations in other projects.
> Added th.device to represent both str and torch.device.

- theseus/geometry/so2.py
Creating the new tensor from `cosine` is better, since our typical use case uses vmap over the optimization variable. The previous version could result in errors in AutodiffCostFunction in some corner cases (@rmurai0610 hit one of these). The caveat is that the new version will fail if we vmap over the points, but there is no easy workaround for this. From conversation with @zou3519 it seems that `functorch` team is working on some better API to lift tensors to their batched versions.
> Minor vmap fix in SO2

- examples/configs/pose_graph/pose_graph_synthetic.yaml
- examples/pose_graph/pose_graph_synthetic.py
- tests/optimizer/linear/test_dense_solver.py
- tests/optimizer/nonlinear/common.py
- theseus/optimizer/autograd/baspacho_sparse_autograd.py
- theseus/optimizer/dense_linearization.py
- theseus/optimizer/linearization.py
- theseus/optimizer/nonlinear/levenberg_marquardt.py
- theseus/optimizer/sparse_linearization.py
- theseus/utils/__init__.py
- theseus/utils/sparse_matrix_utils.py
This PR adds a method to compute `Atb` in the sparse linearization, which we can use for the adaptive damping computation. 
I also sneaked in a change to the PGO example, to make it easier to pass optimizer kwargs.
> Add sparse solvers support to LM adaptive damping

- tests/core/test_vectorizer.py
- tests/test_theseus_layer.py
- theseus/core/objective.py
- theseus/core/vectorizer.py
- theseus/optimizer/dense_linearization.py
- theseus/optimizer/sparse_linearization.py
This will be useful for improving the accept/reject step of LM, and for more complex line search later. 
Closes #231. 
Note that as a consequence of this, this PR changes PGO optimization numerical results because now Objective.error() returns the non-scaled weighted error for `RobustCostFunction`, while the previous version was returning the scaled one.
> Change Objective.error() so it can be vectorized w/o changing vectorized cache

- tests/geometry/functional/test_so3.py
- theseus/geometry/functional/lie_group.py
- theseus/geometry/functional/so3.py
> Add theseus.geometry.functional.so3.inverse()

- theseus/core/objective.py
- theseus/optimizer/linear/linear_optimizer.py
- theseus/optimizer/nonlinear/gauss_newton.py
- theseus/optimizer/nonlinear/levenberg_marquardt.py
- theseus/optimizer/nonlinear/nonlinear_optimizer.py
- theseus/theseus_layer.py
The previous version would adjust the damping depending on whether the step should be accepted or not, but it would nevertheless always take the step. This could result in divergence if the down damping ratio was too aggressive. 
In the new version, if the step should be rejected, it's indeed rejected (and this is computed independently for each batch element).
> Add proper accept/reject logic for LM optimizer

- tests/extlib/test_baspacho.py
- tests/extlib/test_cusolver_lu_solver.py
- tests/extlib/test_mat_mult.py
- tests/optimizer/autograd/test_baspacho_sparse_backward.py
- tests/optimizer/autograd/test_lu_cuda_sparse_backward.py
- theseus/optimizer/autograd/baspacho_sparse_autograd.py
- theseus/optimizer/autograd/cholmod_sparse_autograd.py
- theseus/optimizer/autograd/lu_cuda_sparse_autograd.py
- theseus/optimizer/linear/baspacho_sparse_solver.py
- theseus/optimizer/linear/lu_cuda_sparse_solver.py
- theseus/optimizer/linear_system.py
- theseus/optimizer/sparse_linearization.py
- theseus/utils/__init__.py
- theseus/utils/sparse_matrix_utils.py
Did some clean up of the code in `optimizer/autograd` and `optimizer/linear`, including adding type hints. Most of the changes are variable names and type hints, except for adding `new_empty` in a couple of places, and adding new function for  samping sparse matrices. 
There is some duplicated code in `backward` passes that should be relatively easy to fix, but I'd prefer doing that in a separate smaller PR to avoid introducing bugs. 
Closes #326
> Cleaned up sparse solvers code

- tests/optimizer/nonlinear/test_levenberg_marquardt.py
- tests/test_theseus_layer.py
- theseus/optimizer/nonlinear/levenberg_marquardt.py
- theseus/optimizer/nonlinear/nonlinear_optimizer.py
In this version we sometimes have to recompute the error norm if some steps are rejected, so optimizing error vectorization becomes important again. Will fix in a separate PR.
> Add a workaround for NonlinearOptimizer rejecting all batch steps

- tests/optimizer/autograd/common.py
- tests/optimizer/autograd/test_baspacho_sparse_backward.py
- tests/optimizer/autograd/test_lu_cuda_sparse_backward.py
- tests/test_theseus_layer.py
- theseus/optimizer/autograd/baspacho_sparse_autograd.py
- theseus/optimizer/autograd/lu_cuda_sparse_autograd.py
- theseus/optimizer/sparse_linearization.py
Note that this doesn't changed the extensions themselves. We convert from float to double and back before calling the C++ routines. 
PS: I had to make the same change in the two different solvers, so I really think it's worth unifying the sparse solvers under a common base class. I'll try to find time to do this soon.
> Allow float data to be used with our sparse solver extensions

- tests/optimizer/nonlinear/common.py
- tests/optimizer/test_sparse_linearization.py
- tests/utils/test_utils.py
- theseus/optimizer/dense_linearization.py
- theseus/optimizer/linearization.py
- theseus/optimizer/sparse_linearization.py
- theseus/utils/__init__.py
- theseus/utils/sparse_matrix_utils.py
Backward pass can be made more efficient in GPU if we write a custom CUDA kernel for it, but this should be reasonable enough for now.
> Add a differentiable sparse matrix vector product on top of our ops

- tests/optimizer/nonlinear/common.py
- tests/optimizer/nonlinear/test_levenberg_marquardt.py
- tests/optimizer/test_sparse_linearization.py
- theseus/optimizer/dense_linearization.py
- theseus/optimizer/linearization.py
- theseus/optimizer/nonlinear/levenberg_marquardt.py
- theseus/optimizer/sparse_linearization.py
This adds a linearization diagonal scaling method and implementations for dense and sparse linearization. The sparse implementation could be faster with a custom kernel, to avoid python loop over rows, but this should be good enough to get an initial implementation.
> Add diagonal scaling method and re-enable LM adaptive + ellipsoidal

- theseus/utils/__init__.py
- theseus/utils/utils.py
Removes boilerplate. Can be used as
```python
from thesus.utils import Timer
with Timer("cuda:0") as timer:
some_stuff
print(timer.elapsed_time)
```
> Add a timer util that adapts to a torch.device.

- tests/core/test_vectorizer.py
- theseus/core/vectorizer.py
Previous version would group autodiff costs with different error functions, if the optim vars and aux vars were all of the same type.
> Fix bug in Vectorization of autodiff costs.

- theseus/core/objective.py
Avoids unnecessary extra calls to vectorization update.
> Objective.error() no longer updates vectorization if also_update=False.

- tests/geometry/functional/test_se3.py
- theseus/geometry/functional/se3.py
> Add se3.log()

- tests/core/common.py
- tests/core/test_robust_cost.py
- tests/core/test_vectorizer.py
- tests/embodied/motionmodel/test_double_integrator.py
- tests/optimizer/linearization_test_utils.py
- theseus/__init__.py
- theseus/core/__init__.py
- theseus/core/cost_function.py
- theseus/core/cost_weight.py
- theseus/core/robust_cost_function.py
- theseus/core/variable.py
- theseus/core/vectorizer.py
- theseus/embodied/motionmodel/double_integrator.py
With this feature, the vectorizer is able to compute errors and jacobians only over batch indices that are known to be greater than zero. Preliminary tests on a simple problem indicate savings of ~18% compute time both in CPU and GPU. 
For now I made the feature only applicable inside vectorization, although it might be safe to turn off in general.
> Add support for masking jacobians of zero weights in the batch

- requirements/main.txt
- setup.py
> Fixed error that was preventing requirements versions to be used in setup

- tests/embodied/robot/test_forward_kinematics.py
- theseus/embodied/robot/joint.py
- theseus/embodied/robot/robot.py
> Add device to robot model

- tests/embodied/robot/test_forward_kinematics.py
- theseus/embodied/robot/forward_kinematics.py
- theseus/embodied/robot/joint.py
- theseus/embodied/robot/robot.py
- theseus/labs/lie_functional/se3.py
> Add prismatic joint

- tests/test_theseus_layer.py
The data model was wrong as in it had to two optima, leading to some of the optimizer not able to pass the test. The comments in the file also suggests that the intentional model and actually implemented model were different.
All the current optimizer passes the test with the changed model.
> Change in data model in test_theseus_layer

- tests/test_theseus_layer.py
- tests/utils/test_utils.py
- theseus/theseus_layer.py
- theseus/utils/__init__.py
- theseus/utils/utils.py
Closes #321. 
Not integrated with `TheseusLayer` yet, but I think we can set this up so that the check is (optionally) performed once for each cost function right after the objective's version is fixed. 
cc @xphsean12 as related to #461
> Added utility to automatically check jacobians of a given cost function.

- theseus/geometry/se3.py
Replace `torch.zeros` with `new_zeros` to make log_map vmappable.
This is already fixed in the new api, but it wasn't in the old ones.
> Allow vmap to work on th.SE3 log_map

- theseus/embodied/collision/signed_distance_field.py
Made the boundary value of sdf configurable.
The default was 0 (i.e. solid wall around the map) but this does not make sense in MPC setting, where we may want to encourage the motion planner to explore outside the current local map.
It's not tested yet
> Make SDF boundary value configurable

- examples/lie_labs.py
This PR has a small example illustrating the current features of our new Lie group tensor library for PyTorch. We are looking for feedback on: 
1. **API**: Is it easy to use? Any confusing points? Any source of friction?
2. **Features**: Any features you'd like to see that are not in the planned features below?
3. **Bugs**: Any bugs you noticed?
* A `LieTensor` subclass of `torch.Tensor` serving as entry point.
* SE3 and SO3 groups.
* Implementation of several Lie groups operators, each with custom backward pass: 
* log and exp maps
* adjoint, vee, hat operators
* inverse, compose
* transform_from (convert point from pose to world coordinates)
* Differentiable jacobians to use in optimization libraries (the jacobians are computed in closed form using `torch`, but w/o a custom backward …
> Lie Labs API example

- theseus/labs/lie/functional/se3_impl.py
- theseus/labs/lie/functional/so3_impl.py
> fixed bugs for jacobians of transform_from

- tests/labs/lie/functional/common.py
- tests/labs/lie/functional/test_se3.py
- tests/labs/lie/functional/test_so3.py
- theseus/labs/lie/functional/__init__.py
- theseus/labs/lie/functional/check_contexts.py
- theseus/labs/lie/functional/lie_group.py
- theseus/labs/lie/functional/se3_impl.py
- theseus/labs/lie/functional/so3_impl.py
- theseus/labs/lie/lie_tensor.py
Adds `vmap` support for the functional package of `labs.lie`. I have only tested that `vmap + jacrev` works correctly on `inv`, `exp`, `log`, `compose`.
Requires PyTorch >= 2.0, but backward compatibility is maintained. 
TODO:
> Add `labs.lie` support for `functorch` and `vmap` pt. 1

- theseus/labs/lie/functional/constants.py
- theseus/labs/lie/functional/se3_impl.py
- theseus/labs/lie/functional/so3_impl.py
> Add multi-batch support for SE(3) unary operators

- tests/core/test_robust_cost.py
- theseus/core/robust_cost_function.py
- theseus/core/vectorizer.py
> Added an option to flatten_dims in RobustCostFunction.

- tests/labs/lie/functional/common.py
- tests/labs/lie/functional/test_se3.py
- tests/labs/lie/functional/test_so3.py
- theseus/labs/lie/functional/se3_impl.py
- theseus/labs/lie/functional/so3_impl.py
Missing unit test for gradient ops
> Multi-batch unit tests for Lie groups

- .circleci/config.yml
- build_scripts/build_wheel.sh
- requirements/main.txt
- setup.py
- theseus/__init__.py
- theseus/_version.py
- theseus/core/cost_function.py
> Deprecated torch < 2.0.0.

- tests/theseus_tests/core/test_vectorizer.py
- theseus/geometry/lie_group.py
- theseus/geometry/manifold.py
- theseus/geometry/se2.py
- theseus/geometry/se3.py
- theseus/geometry/so2.py
- theseus/geometry/so3.py
- theseus/utils/examples/pose_graph/dataset.py
> Add `kwarg` to disable manifold checks in constructor

- lie/lie/functional/se3_impl.py
- lie/lie/functional/so3_impl.py
- lie/lie/options.py
> Add extra eps for dlog

- tests/torchlie_tests/functional/common.py
- tests/torchlie_tests/functional/test_se3.py
- tests/torchlie_tests/functional/test_so3.py
- tests/torchlie_tests/test_lie_tensor.py
- theseus/geometry/se3.py
- theseus/geometry/so3.py
- torchlie/torchlie/__init__.py
- torchlie/torchlie/functional/lie_group.py
- torchlie/torchlie/functional/se3_impl.py
- torchlie/torchlie/functional/so3_impl.py
- torchlie/torchlie/lie_tensor.py
> Add untransform

- build_scripts/build_wheel.sh
Thanks to #561 we can now upload wheels to `pypi` for different Python versions (see [example](https://pypi.org/project/theseus-ai/#files)). This PR makes it easier to specify the Python version when running our build script.
> Allow Python version to be passed to build script

- examples/configs/pose_graph/pose_graph_synthetic.yaml
- examples/pose_graph/pose_graph_synthetic.py
- tests/theseus_tests/test_pgo_benchmark.py
- theseus/utils/examples/pose_graph/dataset.py
> fixed the rotation and translation order in pgo datasets

- tests/torchkin_tests/test_forward_kinematics.py
- torchkin/torchkin/forward_kinematics.py
> Temporarily fixed a bug for vmap

- evaluations/time_local_cost_backward.py
- examples/se2_planning.py
- tests/torchlie_tests/functional/common.py
- tests/torchlie_tests/functional/test_se3.py
- tests/torchlie_tests/functional/test_so3.py
- theseus/_version.py
- theseus/embodied/misc/local_cost_fn.py
- theseus/global_params.py
- torchlie/torchlie/__init__.py
- torchlie/torchlie/functional/lie_group.py
- torchlie/torchlie/functional/se3_impl.py
- torchlie/torchlie/functional/so3_impl.py
- torchlie/torchlie/global_params.py
- tutorials/05_differentiable_motion_planning.ipynb
The current autograd operators in `torchlie.functional` result in duplicated computation for function calls such as 
```python
res = torchlie.functional.SO3.log(g, jacobians=jlist)
```
because these are computed as follows:
```python
jac, _= _jlog_impl(group)
res = _log_autograd_fn(group) # repeats all the computation done in `_op_impl`
return res, jac
``` 
This PR adds a wrapper that reuses the computation, while preserving the custom backward implementation, as follows
```python
jac, res_value = _jlog_impl(group)
res_tensor = _log_passthrough_fn(group, res_value, jac[0])
return res_tensor, jac
```
Benchmarking with [this script](https://github.com/facebookresearch/theseus/blob/lep.faster_log_map/evaluations/time_local_cost_backward.py) shows improvements of 15-23% runtime when …
> Faster log map implementation

- tests/theseus_tests/utils/test_utils.py
- theseus/utils/utils.py
The timer now has the option of labeling timing runs, and collect history of times per label. Can also be called with `start()` and `end()` methods, without using as a context manager.
The profiler has now methods to to compile the statistics and dump results to a file.
> Improves to Timer and Profiler utils
